### PR TITLE
Fix flexbox baseline alignment

### LINKED ISSUE #28: Support multiple layout algorithms
**Tracking Issues:**

- Add feature flag for Flexbox: https://github.com/DioxusLabs/taffy/issues/298
- CSS Grid: https://github.com/DioxusLabs/taffy/issues/204
- Morphorm: https://github.com/DioxusLabs/taffy/issues/308

This library will be dramatically more useful if it can be used to support multiple layout strategies. This is useful because:

- it centralizes community effort
- it enables fair benchmarks
- it lets users easily swap out approaches
- it creates the potential for blended layouts in the same app

Must have:
- each layout algorithm lives behind its own feature flag
- this crate provides a relatively unified interface to them
  - a trait seems like the natural fit here 

Nice to have:
- low or zero abstraction overhead
- the ability to nest multiple distinct layout strategies, ala flutter
- competitive benchmarks between the different strategies
- rosetta-stone comparisons of practical examples, demonstrating how to create the same / comparable layouts in different paradigms
- users can create their own layout algorithms using our primitives in an interoperable way

Possible layout algorithms we may want to support:

- hstack / vstack
- Swift-UI style 
- Flutter style
- CSS grid
- Morphorm
- [Cassowary](https://constraints.cs.washington.edu/cassowary/)

### PR DESCRIPTION
**Pull request by nicoburns**
# Objective

- [x] Fix flexbox baseline alignment implementation (fixes baseline alignment tests imported from yoga)
- [x] Refactor flexbox baseline alignment implementation so that it doesn't require directly accessing the layout of descendant nodes other than direct children (required to make it's baseline alignment interoperate with Grid and other layout modes properly)
- [x] Optimise baseline alignment computation so that child baseline are only calculated when necessary

## Context

~Note: This PR depends on #320 which in turn depends on #317~ both now merged!

I did a quick run of the benchmarks vs. `main` to check for regressions, and actually I'm seeing mild performance wins (10% - 30% on some benchmarks) on quite a few of the benchmarks. There is also a ~10% regression on a couple, but those are the very smallest ones that are completing in single-digit microseconds anyway, so I'm not going to worry too much about those (we probably ought to remove those super small ones at some point -  I don't think they're very representative of real-world performance).

## Feedback wanted

Does changing each algorithm's `perform_layout` function to return:

```rust
struct SizeAndBaselines {
   size: Size<f32>,
   first_baseline: Point<Option<f32>>,
}
```

instead of `Size<f32>` as I have done in this PR seem reasonable? This is instead of the 3rd layout method proposed in https://github.com/DioxusLabs/taffy/issues/28#issuecomment-1374941635

### CODE REVIEW

**Comment by nicoburns** [comment]
This still doesn't implement baseline alignment for CSS Grid, but I now think I'd like to merge this without that to unblock #326. These changes (fixing baseline alignment for flexbox, and refactoring the flexbox implementation so that it doesn't require accessing the layout of descendant nodes other than direct children) are worthwhile on their own, and baseline alignment for CSS Grid can follow in another PR.

File: src/compute/flexbox.rs [hunk 1]
```diff
@@ -23,6 +23,34 @@ use crate::tree::LayoutTree;
 #[cfg(feature = "debug")]
 use crate::debug::NODE_LOGGER;
 
+/// The public interface to Taffy's Flexbox algorithm implementation
+pub(crate) struct FlexboxAlgorithm;
```
Comment (alice-i-cecile) [inline src/compute/flexbox.rs:27]: It definitely feels weird that this isn't fully pub, given the comment above.

File: src/compute/flexbox.rs [hunk 2]
```diff
@@ -130,14 +158,14 @@ struct AlgoConstants {
 }
 
 /// Computes the layout of [`LayoutTree`] according to the flexbox algorithm
-pub fn compute(
+pub fn compute_generic(
```
Comment (alice-i-cecile) [inline src/compute/flexbox.rs:161]: This name isn't very clear.

File: src/compute/grid/mod.rs [hunk 3]
```diff
@@ -32,19 +32,48 @@ mod track_sizing;
...
+}
+
 /// Grid layout algorithm
 /// This consists of a few phases:
 ///   - Resolving the explicit grid
 ///   - Placing items (which also resolves the implicit grid)
 ///   - Track (row/column) sizing
 ///   - Alignment & Final item placement
-pub fn compute(
+pub fn compute_generic(
```
Comment (alice-i-cecile) [inline src/compute/grid/mod.rs:69]: Ditto on the name here.

Comment (alice-i-cecile) [inline src/compute/grid/mod.rs:69]: Can / should this method be factored into the LayoutAlgorithm trait?

File: src/compute/leaf.rs [hunk 4]
```diff
@@ -12,16 +13,43 @@ use crate::tree::LayoutTree;
 #[cfg(feature = "debug")]
 use crate::debug::NODE_LOGGER;
 
+/// The public interface to Taffy's Lead node algorithm implementation
```
Comment (alice-i-cecile) [inline src/compute/leaf.rs:16]:
```suggestion
/// The public interface to Taffy's leaf node algorithm implementation
```

File: src/compute/leaf.rs [hunk 5]
```diff
@@ -12,16 +13,43 @@ use crate::tree::LayoutTree;
...
+        available_space: Size<AvailableSpace>,
+        sizing_mode: SizingMode,
+    ) -> Size<f32> {
+        compute_generic(tree, node, known_dimensions, parent_size, available_space, sizing_mode).size
+    }
+}
+
 /// Compute the size of a leaf node (node with no children)
-pub(crate) fn compute(
+pub(crate) fn compute_generic(
```
Comment (alice-i-cecile) [inline src/compute/leaf.rs:45]: Ditto on name, and this is definitely making me suspicious that this should be in the trait.

File: src/compute/mod.rs [hunk 6]
```diff
@@ -45,86 +48,210 @@ pub fn compute_layout(
...
+        known_dimensions: Size<Option<f32>>,
+        parent_size: Size<Option<f32>>,
+        available_space: Size<AvailableSpace>,
+        sizing_mode: SizingMode,
+    ) -> SizeAndBaselines;
+}
+
+/// The public interface to a generic algorithm that abstracts over all of Taffy's algorithms
+/// and applies the correct one based on the `Display` style
+pub struct GenericAlgorithm;
```
Comment (alice-i-cecile) [inline src/compute/mod.rs:79]: Hmm. I'm not very happy with this naming / docs. Maybe something like `UnifyingLayoutAlgorithm`?

File: src/layout.rs [hunk 7]
```diff
@@ -22,8 +22,17 @@ pub enum SizingMode {
     InherentSize,
 }
 
+/// A struct containing both the size of a node and it's first baseline in each dimension (if it has any)
```
Comment (alice-i-cecile) [inline src/layout.rs:25]: This could use a simple definition of what a "baseline" is.

File: src/layout.rs [hunk 8]
```diff
@@ -22,8 +22,17 @@ pub enum SizingMode {
...
+#[derive(Debug, Copy, Clone)]
+pub struct SizeAndBaselines {
+    /// The size of the node
+    pub size: Size<f32>,
+    /// The first baseline of the node in each dimension
```
Comment (alice-i-cecile) [inline src/layout.rs:30]:
```suggestion
    /// The first baseline of the node in each dimension, if any
```

File: src/compute/grid/mod.rs (hunk 3 above)
Comment (nicoburns) [reply src/compute/grid/mod.rs:69]: Well the idea is that the `LayoutAlgorithm` trait has separate `perform_layout` and `measure_size` functions for clarity, but our implementations share one function for both (and my thinking was that it makes sense to keep it that way, but I'm not sure about that). If we don't then we get a bunch of repeated code.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Some feedback on structure and docs. I would like to get this merged quickly though, so feel free to defer some of the work (e.g. the trait refactor) to a follow-up PR.

File: src/compute/flexbox.rs (hunk 1 above)
Comment (nicoburns) [reply src/compute/flexbox.rs:27]: This one is actually fixed in #326. I'd probably rather leave that change there if that's ok. Because this PR isn't currently changing our public API at all, whereas #326 is already making significant changes to the public API already.

File: src/layout.rs (hunk 7 above)
Comment (nicoburns) [reply src/layout.rs:25]: Fixed

File: src/compute/mod.rs (hunk 6 above)
Comment (nicoburns) [reply src/compute/mod.rs:79]: This struct actually disappears in my latest version of #326, as I've made the "generic" algorithm and the "leaf" algorithm operate on `&mut Taffy` rather than `&mut impl LayoutTree` (so they don't fit the `LayoutAlgorithm` trait anymore). This allows us to remove measure_funcs from the `LayoutTree` trait and make them an implementation detail of our `Taffy` storage implementation.

**Comment by nicoburns** [comment]
@alice-i-cecile I've renamed the `compute_generic` functions back to `compute`, which is what they were already called. So I think it can now safely be said that the interface is no worse than it was. In any case, as these traits/functions are currently private, I'm not going to worry about too much (we can easily change this later if we want to). I suggest we bikeshed this in #326 (which does make the `LayoutAlgorithm` trait public) and also makes major changes to the public interface exposed through the `LayoutTree` trait.

Is there anything else blocking this?

File: src/compute/flexbox.rs (hunk 1 above)
Comment (alice-i-cecile) [reply src/compute/flexbox.rs:27]: Great that's fine by me.

File: src/compute/grid/mod.rs (hunk 3 above)
Comment (alice-i-cecile) [reply src/compute/grid/mod.rs]: Ah got it. I'm fine to keep it as is then.

File: src/compute/mod.rs (hunk 6 above)
Comment (alice-i-cecile) [reply src/compute/mod.rs:79]: Good I'm fine to wait.

**Comment by alice-i-cecile** [comment]
Nope, this now LGTM.

**Review by alice-i-cecile — APPROVED** [review]
