### PR TITLE
Import yoga tests

### LINKED ISSUE #285: Sync generated test suite with Yoga
CC: @NickGerleman

## What problem does this solve or what need does it fill?

The more tests we have the better! Our generated test system is derived from Yoga's and the format is mostly compatible. And Yoga has a bunch of tests in their system that we don't have (some of these may not be applicable, but many of them will be). We have also added tests that Yoga doesn't have, and we should be good OSS citizens and make them available for Yoga.

## What solution would you like?

- Import tests from Yoga that we are missing, and fix any relevant bugs.
- Export any tests that Yoga are missing back to the Yoga project.

## Tests Taffy is missing

As of #320, Taffy has now imported all of Yoga's tests, however the following tests are disabled (by prefixing the filename with an "x") because they are failing:

```diff
-absolute_child_with_cross_margin
-absolute_child_with_main_margin
-absolute_layout_percentage_height
-absolute_layout_row_width_height_end_bottom
-align_baseline_child_margin
-align_baseline_child_margin_percent
-align_baseline_child_multiline_no_override_on_secondline
-align_baseline_child_multiline_override
-align_baseline_child_padding
-align_baseline_multiline
-align_baseline_multiline_row_and_column
-align_content_flex_end
-align_content_not_stretch_with_align_items_stretch
-display_none_absolute_child
-display_none_with_position_absolute
-do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent
-justify_content_column_min_height_and_margin
-justify_content_colunn_max_height_and_margin
-margin_auto_start_and_end
-margin_auto_start_and_end_column
-margin_end
-margin_start
-position_root_with_rtl_should_position_withoutdirection
-rounding_inner_node_controversy_combined
-rounding_inner_node_controversy_horizontal
```

## Tests Yoga is missing

This list excludes CSS Grid tests as out of scope:

```diff
+absolute_layout_child_order
+absolute_layout_no_size
+align_baseline_child_top2
+align_baseline_multiline_column2
+align_baseline_nested_child
+align_content_space_around_single_line
+align_content_space_around_wrapped
+align_content_space_between_single_line
+align_content_space_between_wrapped
+align_content_space_evenly_single_line
+align_content_space_evenly_wrapped
+align_items_center_with_child_margin
+align_items_center_with_child_top
+border_no_child
+container_with_unsized_child
+flex_basis_and_main_dimen_set_when_flexing
+flex_basis_larger_than_content_column
+flex_basis_larger_than_content_row
+flex_basis_slightly_smaller_then_content_with_flex_grow_large_size
+flex_basis_smaller_than_content_column
+flex_basis_smaller_than_content_row
+flex_basis_smaller_than_main_dimen_column
+flex_basis_smaller_than_main_dimen_row
+flex_basis_smaller_then_content_with_flex_grow_large_size
+flex_basis_smaller_then_content_with_flex_grow_small_size
+flex_basis_smaller_then_content_with_flex_grow_unconstraint_size
+flex_basis_smaller_then_content_with_flex_grow_very_large_size
+flex_basis_unconstraint_column
+flex_basis_unconstraint_row
+flex_grow_flex_basis_percent_min_max
+flex_shrink_by_outer_margin_with_max_size
+gap_column_gap_flexible_undefined_parent
+gap_column_gap_inflexible_undefined_parent
+gap_column_gap_percentage_cyclic_partially_shrinkable
+gap_column_gap_percentage_cyclic_shrinkable
+gap_column_gap_percentage_cyclic_unshrinkable
+gap_column_gap_percentage_flexible
+gap_column_gap_percentage_flexible_with_padding
+gap_column_gap_percentage_inflexible
+gap_column_gap_row_gap_wrapping
+gap_percentage_row_gap_wrapping
+justify_content_column_min_height_and_margin_bottom
+justify_content_column_min_height_and_margin_top
+margin_left
+margin_right
+max_height_overrides_height_on_root
+max_width_overrides_width_on_root
+measure_child
+measure_child_absolute
+measure_child_constraint
+measure_child_constraint_padding_parent
+measure_child_with_flex_grow
+measure_child_with_flex_shrink
+measure_flex_basis_overrides_measure
+measure_height_overrides_measure
+measure_remeasure_child_after_growing
+measure_remeasure_child_after_shrinking
+measure_remeasure_child_after_stretching
+measure_root
+measure_stretch_overrides_measure
+measure_width_overrides_measure
+min_height_overrides_height_on_root
+min_height_overrides_max_height
+min_width_overrides_max_width
+min_width_overrides_width_on_root
+overflow_cross_axis
+overflow_main_axis
+padding_align_end_child
+padding_no_child
+percentage_moderate_complexity
+percentage_size_based_on_parent_inner_size
+percentage_size_of_flex_basis
+relative_position_should_not_nudge_siblings
+rounding_flex_basis_flex_grow_row_width_of_100
+rounding_fractial_input_1
+rounding_fractial_input_2
+rounding_fractial_input_3
+rounding_fractial_input_4
+size_defined_by_child
+size_defined_by_child_with_border
+size_defined_by_child_with_padding
+size_defined_by_grand_child
+width_smaller_then_content_with_flex_grow_large_size
+width_smaller_then_content_with_flex_grow_small_size
+width_smaller_then_content_with_flex_grow_unconstraint_size
+width_smaller_then_content_with_flex_grow_very_large_size
+wrap_reverse_column
+wrap_reverse_row
 ```

### PR DESCRIPTION
**Pull request by nicoburns**
# Objective

Fixes #285.

## Changes made

- Add a re-runnable diff script that also does some munging of the test names to make them match up when they have diverged.
- Add an import script. This is pretty rough, but I feel like standards need not be so high for something that is run "offline" and rarely. It compiles, runs, it's formatted and linted.
- Import ALL yoga tests (including the ones from https://github.com/facebook/yoga/pull/1194 that they haven't landed on master yet)

## Notes

- I have imported all tests, but I have not made any attempt to fix failing ones. I feel like this would be best tackled in follow up PRs that tackle a group of related failing tests without trying to fix everything at once, as I imagine some will be a lot more difficult than other.
- I have also not made any attempt to diff the tests to check for differences in the specification of tests that we both have. This would also be useful thing to do, but it's a much more complex task (diffing HTML is non-trivial).

### CODE REVIEW

File: scripts/import-yoga-tests/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                        name.replace("column_gap", "gap_column_gap")
+                    };
+                    YogaFixture { file_name: file_name.clone(), name: taffy_name, content: name_replace_snippet }
+                })
+                .collect::<Vec<_>>()
+        })
+        .collect();
+
+    for fixture in yoga_fixtures {
+        if !taffy_fixture_names.contains(&fixture.name) {
```
Comment (alice-i-cecile) [inline scripts/import-yoga-tests/src/main.rs:69]: What happens if the fixtures are updated but not renamed? Won't they get out of sync with this strategy?

Comment (nicoburns) [reply scripts/import-yoga-tests/src/main.rs:69]: > Won't they get out of sync with this strategy?

Yes. They likely already are. This is at least a quick way to get us tests we were entirely missing though. I guess we'll need to actually parse the HTML/CSS to sync updates.

Comment (alice-i-cecile) [reply scripts/import-yoga-tests/src/main.rs:69]: Makes sense. What's the cost to rebuilding them completely every time?

Comment (nicoburns) [reply scripts/import-yoga-tests/src/main.rs:69]: > What's the cost to rebuilding them completely every time?

As in treating Yoga's version as the source of truth and overwriting any changes we might have made? There's no technical blocker on that. I think the main problem with that would be that it would make it hard for us to maintain any changes that we actually need. As an example: I removed whitespace from a couple of tests when I added support for sizing text nodes. It would be nice if there was a single source of truth though, and I suppose that could be managed by just being selective with when we sync and which changes we commit when we sync.

File: test_fixtures/android_news_feed.html [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    Test description
+  </title>
+<head/>
+<body>
+
+  <div id="test-root" layout="width: 1080; height: 444; top: 0; left: 0;" style="align-content: stretch; flex-shrink: 0; width: 1080px; " >
+    <div layout="width: 1080; height: 444; top: 0; left: 0;" style="flex-shrink: 0; " >
+      <div layout="width: 1080; height: 444; top: 0; left: 0;" style="align-content: stretch; " >
+        <div layout="width: 1080; height: 226; top: 0; left: 0;" style="align-content: stretch; " >
+          <div layout="width: 1044; height: 202; top: 24; left: 36;" style="flex-direction: row; align-items: flex-start; align-content: stretch; margin-top: 24px; margin-start: 36px; " >
```
Comment (NickGerleman) [inline test_fixtures/android_news_feed.html:16]: The "margin-start" here is not a valid CSS property, and Yoga's test generator did some funky things with it. But it's effectively the same as "margin-inline-start" for any case that isn't a vertical writing direction (which I don't think Yoga or Taffy support).

Comment (nicoburns) [reply test_fixtures/android_news_feed.html:16]: Ah, that's useful to know. Taffy actually doesn't support `margin-inline-start` either (it has `margin-left`). I'm guessing Yoga also doesn't support this and the test generator just converts it to left/right?

Comment (nicoburns) [reply test_fixtures/android_news_feed.html:16]: I did a test run overwriting all of Taffy's test with Yoga's (where there as an equivalent) to see what the diff would be like, and there were quite a few differences. In addition to the start/end vs. left/right thing, the main one's were due to Yoga defaulting to `flex-direciton: column` while Taffy defaults to `flex-direction: row`. Many of a Taffy's tests had an explicit flex-direction added to account for this. And some of them had width/height swapped to account for it in a different way. I suspect we'll need to add explicit `flex-direction` everywhere if we want to unify the test suites.

File: scripts/import-yoga-tests/src/main.rs (hunk 1 above)
Comment (alice-i-cecile) [reply scripts/import-yoga-tests/src/main.rs:69]: Sounds reasonable: I'm fine with whatever you pick here.

File: test_fixtures/android_news_feed.html (hunk 2 above)
Comment (NickGerleman) [reply test_fixtures/android_news_feed.html:16]: > Ah, that's useful to know. Taffy actually doesn't support `margin-inline-start` either (it has `margin-left`). I'm guessing Yoga also doesn't support this and the test generator just converts it to left/right?

Yoga does have support for flow-relative margin, padding, etc. The API at the Yoga level looks like `YGNodeStyleSetMargin`, accepting a `YGEdge`, which can be (in order of precedence) a cardinal direction (e.g. `YGEdgeLeft`), a flow-relative direction (e.g. `YGEdgeStart`), an axis (e.g. `YGEdgeHorizontal`), or `YGEdgeAll`.

React Native historically historically mapped `YGEdgeStart` to `marginStart`, etc, but we recently added `marginInlineStart`, `marginBlockStart`, etc to be conformant with browsers.

Comment (NickGerleman) [reply test_fixtures/android_news_feed.html:16]: Re defaults, Yoga supports a `YGConfig` option `UseWebDefaults`. There are a couple other differences in the default style which that overrides. My historical understanding was that it was to eventually become the default, but the work never materialized.

Comment (nicoburns) [reply test_fixtures/android_news_feed.html:16]: > a flow-relative direction (e.g. YGEdgeStart), an axis (e.g. YGEdgeHorizontal)"

Wouldn't you need a flow-relative direciton AND an axis to fully specify an edge? (`YGEdgeStart` by itself is ambiguous. You'd need `YGEdgeInlineStart`, no?).

> The API at the Yoga level looks like YGNodeStyleSetMargin, accepting a YGEdge, which can be (in order of precedence) a cardinal direction (e.g. YGEdgeLeft), a flow-relative direction (e.g. YGEdgeStart), an axis (e.g. YGEdgeHorizontal), or YGEdgeAll.

Do you actually store the flow-relative styles (e.g. `margin-inline-start`) separately from the absolute styles (e.g. `margin-left`)? i.e. would it compute the correct layout if a user starts toggling the RTL flag after setting the styles? And if it does do that, how are you dealing with the effective doubling of memory usage that this entails? Are you just eating that cost? I tried looking through the yoga source, and it looked to me that the size of the margin property in`YGStyle` was equal to the number of variants in the `YGEdge`, but given the variants in YGEdge that didn't make any sense to me.

The templated C++ type definitions were going over my head a bit though, so it's possible I wasn't understanding this correctly.

Comment (nicoburns) [reply test_fixtures/android_news_feed.html:16]: > Re defaults, Yoga supports a YGConfig option UseWebDefaults. There are a couple other differences in the default style which that overrides. My historical understanding was that it was to eventually become the default, but the work never materialized.

Perhaps it would make sense to make this the default specifically for the test suite? (updating the test fixtures accordingly so that the actual tests don't change).

Comment (NickGerleman) [reply test_fixtures/android_news_feed.html]: > Wouldn't you need a flow-relative direciton AND an axis to fully specify an edge? (YGEdgeStart by itself is ambiguous. You'd need YGEdgeInlineStart, no?).

Start/End only ever refer to the horizontal axis, and just picks Left/Right based on RTL. But yeah,  the style has distinct inputs for padding, margin, etc per YGEdge, and a specific precedence when multiple  inputs are present which may overlap the same physical edge. It would be reevaluated if laid out as RTL. Yoga also weirdly treats both YGEdgeLeft and YGEdgeStart as effecting the right side of a box with flexDirection: "row-reverse" which is inconsistent with browsers. 

Yoga's precedence logic based on specificity is one difference from browsers, where CSS properties are ordered and if there is overlap, the last assignment wins (e.g. "margin" takes precedence over "marginLeft" if it comes after).

Comment (NickGerleman) [reply test_fixtures/android_news_feed.html]: > Perhaps it would make sense to make this the default specifically for the test suite? (updating the test fixtures accordingly so that the actual tests don't change).

I think updating that would probably make sense. The existing passing fixtures must be explicit enough to set styles that are interpreted the came between both browsers and Yoga in its normal layout mode, but I don't know if we want that requirement.

Comment (nicoburns) [reply test_fixtures/android_news_feed.html]: > If you're having to add column direction, was Yoga's test generator doing that in the outer HTML too?

I haven't actually checked that yet. I've gone through and added all the `flex-direction: column`s. But actually, all of those tests were already passing. So it's possible that the missing flex-directions weren't actually making a meaningful difference to the tests. I'd still be more comfortable if the tests are unambiguously specified though.

Comment (nicoburns) [reply test_fixtures/android_news_feed.html]: > Start/End only ever refer to the horizontal axis, and just picks Left/Right based on RTL.

Ah, I guess that makes sense given that IIRC Yoga supports RTL but not vertical writing modes. The variants are confusingly named though! I'm guessing that might the sort of thing it might be more possible to make breaking changes to (as it will turn into a compile error)?

> Yoga also weirdly treats both YGEdgeLeft and YGEdgeStart as effecting the right side of a box with flexDirection: "row-reverse" which is inconsistent with browsers.

That is weird. As documented in https://github.com/DioxusLabs/taffy/issues/307, it does work that way for the `flex-start` alignment value, but there is also a separate `start` which isn't affected by the the `flex-direction`, and it definitely shouldn't do that for `left`!

Comment (nicoburns) [reply test_fixtures/android_news_feed.html]: > If you're having to add column direction, was Yoga's test generator doing that in the outer HTML too?

@NickGerleman I looked into this, and the stylesheet that Yoga uses when generating tests applies this default. See https://github.com/facebook/yoga/blob/main/gentest/test-template.html#L28

**Comment by nicoburns** [comment]
@alice-i-cecile Requested changes made. Filtering out tests beginning with `x` happens here https://github.com/DioxusLabs/taffy/blob/main/scripts/gentest/src/main.rs#L27. And the gentest script completely overwrites the generated test directory when it runs so that will also delete any already existing generated tests.

File: test_fixtures/align_baseline_multiline_column.html [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+<head>
+  <script src="../scripts/gentest/test_helper.js"></script>
+  <link rel="stylesheet" type="text/css" href="../scripts/gentest/test_base_style.css">
+  <title>
+    Test description
+  </title>
+<head/>
+<body>
+
+<!-- Broken after Chrome behavior change -->
```
Comment (Weibye) [inline test_fixtures/align_baseline_multiline_column.html:12]: Does this mean that the test generated by the gentest will be incorrect? What is the correct course of action in these cases? 

Do we disable the test or do we keep it as chrome's new behaviour is what we are targeting? 
I do suspect once you throw multiple browsers into the mix and compare them the picture becomes a lot more complicated.

**Review by Weibye — APPROVED** [review]
Good work as usual! The increased test coverage is surely going to be valuable in guiding rework and new features.

File: test_fixtures/align_baseline_multiline_column.html (hunk 3 above)
Comment (nicoburns) [reply test_fixtures/align_baseline_multiline_column.html]: Actually these comments come directly from the yoga repo (where these tests are commented out). We actually pass these tests just fine (and https://github.com/DioxusLabs/taffy/pull/325 fixes the baseline alignment tests we weren't already passing). And in the case where we don't, our policy (at least for now) is just to update to the latest "web compatible" behaviour. On the other hand Yoga doesn't want to change their exisiting behaviour because it's used in react native which has a huge install base whose UIs might all end up broken by such a change.

I've removed the comments from our codebase.

**Review by alice-i-cecile — APPROVED** [review]
